apiVersion: "apiextensions.k8s.io/v1"
kind: CustomResourceDefinition
metadata:
  name: pgclusters.stable.badsysadm.com
spec:
  group: stable.badsysadm.com
  versions: 
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hosts:
                  type: array
                  items:
                    type: string
                secret:
                  type: string
  scope: Namespaced
  names:
    plural: pgclusters
    singular: pgcluster
    kind: PGCluster
    shortNames:
    - pgc

---

apiVersion: "stable.badsysadm.com/v1"
kind: PGCluster
metadata:
  name: patroni11
spec:
  hosts:
    - 192.168.0.1:5432
    - 192.168.0.2:5432
    - 192.168.0.3:5432
  secret: ipex-pg-admin

---

apiVersion: v1
kind: Secret
metadata:
  name: ipex-pg-admin
type: Opaque
data:
  username: ZXhhcGxlCg==
  password: ZXhhcGxlCg==
  database: ZXhhcGxlCg==

